### ISSUE TITLE
Frontend log content should not include stack trace

### ISSUE THREAD

**Issue by mpo-mjolner** [Open-Pectus/Open-Pectus#425]
When executing the malformed pcode `Wait : 3 s` the frontend should add something like
`Invalid instruction: Wait : 3 s`
to the error list.

Instead it adds this stack trace:
`08-14 09:06:46.170: [error] Interpretation error Traceback (most recent call last): File "C:\Projects\Novo\Open-Pectus\openpectus\engine\engine.py", line 247, in tick self._interpreter.tick(self._tick_time, self._tick_number) File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 258, in tick next(self.process_instr) File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 202, in _interpret yield from self.visit(tree) File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 406, in visit yield from result File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 419, in visit_PProgram yield from self._visit_children(node.children) File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 369, in _visit_children yield from self.visit(child) File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 402, in visit result = super().visit(node) ^^^^^^^^^^^^^^^^^^^ File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 45, in visit return visitor(node) ^^^^^^^^^^^^^ File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 692, in visit_PErrorInstruction raise NodeInterpretationError(node, f"Invalid instruction '{node.code}'") openpectus.lang.exec.errors.NodeInterpretationError`

The error must be in the engine error handling and/or collection.

**Comment by mpo-mjolner** [comment]
We probably need a mapping that decides which errors are sent to the client and how thet are formatted (incl. stripping stack traces)
