### ISSUE TITLE
Mark tag error

### ISSUE THREAD

**Issue by mpo-mjolner** [Open-Pectus/Open-Pectus#442]
The following PCode fails to run
```
Mark: foo
Watch: Mark = foo
    Mark: foo was marked
```
Exception:
Traceback (most recent call last):
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 273, in tick
    work_done = self._run_interrupt_handlers()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 225, in _run_interrupt_handlers
    next(handler)
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 244, in _create_interrupt_handler
    yield from self.visit(node)
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 413, in visit
    yield from result
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 613, in visit_PWatch
    yield from self.visit_WatchOrAlarm(node)
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 641, in visit_WatchOrAlarm
    condition_result = self._evaluate_condition(node)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 332, in _evaluate_condition
    assert not c.error, f"Error parsing condition '{c.condition_str}'"
AssertionError: Error parsing condition 'Mark = foo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\Novo\Open-Pectus\openpectus\engine\engine.py", line 249, in tick
    self._interpreter.tick(self._tick_time, self._tick_number)
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 277, in tick
    raise InterpretationError(message=str(ae), exception=ae)
openpectus.lang.exec.errors.InterpretationError
ERROR:openpectus.engine.engine.frontend:Error parsing condition 'Mark = foo'
INFO:openpectus.engine.engine:Engine Paused because of error

Even this fails to run
`Watch: Mark = 2`

Exception:
ERROR:openpectus.lang.exec.pinterpreter:Interpreter error in interrupt handler
Traceback (most recent call last):
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 641, in visit_WatchOrAlarm
    condition_result = self._evaluate_condition(node)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 337, in _evaluate_condition
    tag_value = tag.as_quantity()
                ^^^^^^^^^^^^^^^^^
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\tags.py", line 216, in as_quantity
    return pint.Quantity(self.value, self.unit)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mpo\Anaconda3\envs\pectus\Lib\site-packages\pint\facets\plain\quantity.py", line 194, in __new__
    raise ValueError(
ValueError: Expression to parse as PlainQuantity cannot be an empty string.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 273, in tick
    work_done = self._run_interrupt_handlers()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 225, in _run_interrupt_handlers
    next(handler)
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 244, in _create_interrupt_handler
    yield from self.visit(node)
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 413, in visit
    yield from result
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 613, in visit_PWatch
    yield from self.visit_WatchOrAlarm(node)
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 645, in visit_WatchOrAlarm
    raise NodeInterpretationError(node, "Error evaluating condition: " + str(ex))
openpectus.lang.exec.errors.NodeInterpretationError
ERROR:openpectus.engine.engine:Interpretation error
Traceback (most recent call last):
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 641, in visit_WatchOrAlarm
    condition_result = self._evaluate_condition(node)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 337, in _evaluate_condition
    tag_value = tag.as_quantity()
                ^^^^^^^^^^^^^^^^^
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\tags.py", line 216, in as_quantity
    return pint.Quantity(self.value, self.unit)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mpo\Anaconda3\envs\pectus\Lib\site-packages\pint\facets\plain\quantity.py", line 194, in __new__
    raise ValueError(
ValueError: Expression to parse as PlainQuantity cannot be an empty string.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\Novo\Open-Pectus\openpectus\engine\engine.py", line 249, in tick
    self._interpreter.tick(self._tick_time, self._tick_number)
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 273, in tick
    work_done = self._run_interrupt_handlers()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 225, in _run_interrupt_handlers
    next(handler)
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 244, in _create_interrupt_handler
    yield from self.visit(node)
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 413, in visit
    yield from result
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 613, in visit_PWatch
    yield from self.visit_WatchOrAlarm(node)
  File "C:\Projects\Novo\Open-Pectus\openpectus\lang\exec\pinterpreter.py", line 645, in visit_WatchOrAlarm
    raise NodeInterpretationError(node, "Error evaluating condition: " + str(ex))
openpectus.lang.exec.errors.NodeInterpretationError
ERROR:openpectus.engine.engine.frontend:Error evaluating condition: Expression to parse as PlainQuantity cannot be an empty string.

**Comment by mpo-mjolner** [comment]
Per #433 the behavior has changed. It no longer fails. However, since the Mark tag is automatically cleared every few ticks, the example makes no sense because it cannot be predicted when the Mark tag is cleared so the Watch condition is not predictable.

**Comment by mpo-mjolner** [comment]
Did add one change that allows parsing strings as tag values.
